//
// Created by gemin on 13/11/2023.
//

#ifndef RICORSIONEMATEMATICA_FACTORIALRECUR_H
#define RICORSIONEMATEMATICA_FACTORIALRECUR_H
long recursiveFactorial(int n);
#endif //RICORSIONEMATEMATICA_FACTORIALRECUR_H
